# This is a basic workflow to help you get started with Actions

name: Newman Run

on:
  push:
    branches:
    - master
    - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: matt-ball/newman-action@master
        with:
          collection: demoblaze.postman_collection.json
          iterationData: data.csv 
          folder: Data-driven
          reporters: '["cli", "html"]'
